name: Test

on:
  workflow_dispatch:

jobs:

  # Debug job to print branch name
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print branch name
        run: 'echo "Branch to deploy: ${{ github.ref }}"'
