name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "builds-branch" ]
  pull_request:
    branches: [ "builds-branch" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get install libevent-dev
        sudo apt-get install asciidoc
        sudo apt-get install tree
    - name: Autogen
      run: ./autogen.sh
    - name: Configure
      run: ./configure
    - name: Make
      run: make
    - name: Debug
      run: make
    - name: Build dir tree
      run: tree
